import Login from "../../../views/components/login/Login.vue";
import {
    UserSquare,
    CreditCard,
    Package,
    ShoppingCart,
    Banknote,
    BookAudio,
    Video,
    Image,
} from "lucide-vue-next";

export const RouteNames = {
    Login: "login",
    AdminsList: "admin-list",
    AddAdmin: "add-admin",
    ViewAdmin: "view-admin",
    EditAdmin: "edit-admin",
    UsersList: "user-list",
    AddUser: "add-user",
    ViewUser: "view-user",
    EditUser: "edit-user",
    PaymentMethodsList: "payment-methods-list",
    AddPayment: "add-payment",
    ViewPayment: "view-payment",
    EditPayment: "edit-payment",
    PackagesList: "packages-list",
    PurchasesList: "purchases-list",
    DepositsList: "deposits-list",
    CoursesList: "courses-list",
    AddCourse: "add-course",
    ViewCourse: "view-course",
    EditCourse: "edit-course",
    CourseLevelsList: "course-levels-list",
    AddCourseLevel: "add-course-level",
    ViewCourseLevel: "view-course-level",
    EditCourseLevel: "edit-course-level",
    CourseCategoriesList: "course-categories-list",
    LessonDaysList: "lesson-days-list",
    AddLessonDay: "add-lesson-day",
    ViewLessonDay: "view-lesson-day",
    EditLessonDay: "edit-lesson-day",
    RestDayVideosList: "rest-videos-list",
    AddRestDayVideo: "add-rest-video",
    ViewRestDayVideo: "view-rest-video",
    EditRestDayVideo: "edit-rest-video",
    WalkInsList: "walk-ins-list",
    FeaturedImagesList: "user-list",
    AddFeaturedImage: "add-user",
    ViewFeaturedImage: "view-user",
    EditFeaturedImage: "edit-user",
    Unauthorized: "unauthorized",
};

export const routes = [
    {
        path: "/",
        name: RouteNames.Login,
        component: Login,
    },
    {
        label: "Admin",
        name: "admin_group",
        icon: UserSquare,
        route: "/auth/admins",
        children: [
            {
                label: "Admin List",
                name: RouteNames.AdminsList,
                header: "Admin Management",
                route: "/auth/admins",
            },
            {
                label: "",
                name: RouteNames.AddAdmin,
                header: "Add Admin",
                route: "/auth/admins/add",
            },
            {
                label: "",
                name: RouteNames.EditAdmin,
                header: "Edit Admin",
                route: "",
            },
            {
                label: "",
                name: RouteNames.ViewAdmin,
                header: "View Admin",
                route: "",
            },
        ],
    },
    {
        label: "User",
        name: "user_group",
        icon: UserSquare,
        route: "/auth/users",
        children: [
            {
                label: "User List",
                name: RouteNames.UsersList,
                header: "User Management",
                route: "/auth/users",
            },
            {
                label: "",
                name: RouteNames.AddUser,
                header: "Add User",
                route: "/auth/users/add",
            },
            {
                label: "",
                name: RouteNames.EditUser,
                header: "Edit User",
                route: "",
            },
            {
                label: "",
                name: RouteNames.ViewUser,
                header: "View User",
                route: "",
            },
        ],
    },
    {
        label: "Payment Method",
        name: "payment_method_group",
        icon: CreditCard,
        route: "/auth/payment-methods",
        children: [
            {
                label: "Payment Methods",
                name: RouteNames.PaymentMethodsList,
                header: "Payment Method Management",
                route: "/auth/payment-methods",
            },
            {
                label: "",
                name: RouteNames.AddPayment,
                header: "Add Payment Method",
                route: "/auth/payment-methods/add",
            },
            {
                label: "",
                name: RouteNames.EditPayment,
                header: "Edit Payment Method",
                route: "",
            },
            {
                label: "",
                name: RouteNames.ViewPayment,
                header: "View Payment Method",
                route: "",
            },
        ],
    },
    {
        label: "Package",
        name: "package_group",
        icon: Package,
        route: "/auth/packages",
        children: [
            {
                label: "Package List",
                name: RouteNames.PackagesList,
                header: "Package Management",
                route: "/auth/packages",
            },
        ],
    },
    {
        label: "Purchase",
        name: "purchase_group",
        icon: ShoppingCart,
        route: "/auth/purchases",
        children: [
            {
                label: "Purchase List",
                name: RouteNames.PurchasesList,
                header: "Purchase Management",
                route: "/auth/purchases",
            },
        ],
    },
    {
        label: "Deposit Transaction",
        name: "deposit_group",
        icon: Banknote,
        route: "/auth/deposits",
        children: [
            {
                label: "Deposit Transaction List",
                name: RouteNames.DepositsList,
                header: "Deposit Transaction Management",
                route: "/auth/deposits",
            },
        ],
    },
    {
        label: "Course",
        name: "course_group",
        icon: BookAudio,
        route: "/auth/courses",
        children: [
            {
                label: "Category List",
                name: RouteNames.CourseCategoriesList,
                header: "Categories Management",
                route: "/auth/categories",
            },
            {
                label: "Course List",
                name: RouteNames.CoursesList,
                header: "Course Management",
                route: "/auth/courses",
            },
            {
                label: "",
                name: RouteNames.AddCourse,
                header: "Add Course",
                route: "/auth/courses/add",
            },
            {
                label: "",
                name: RouteNames.EditCourse,
                header: "Edit Course",
                route: "",
            },
            {
                label: "",
                name: RouteNames.ViewCourse,
                header: "View Course",
                route: "",
            },
        ],
    },
    {
        label: "",
        name: "lesson_day_group",
        route: "/auth/lesson-days",
        children: [
            {
                label: "",
                name: RouteNames.LessonDaysList,
                header: "Lesson Days Management",
                route: "/auth/course-level/:courseLevelId/lesson-days",
            },
            {
                label: "",
                name: RouteNames.AddLessonDay,
                header: "Add Lesson Day",
                route: "/auth/course-level/:courseLevelId/lesson-days/add",
            },
            {
                label: "",
                name: RouteNames.EditLessonDay,
                header: "Edit Lesson Day",
                route: "/auth/course-level/:courseLevelId/lesson-days/:id/edit",
            },
            {
                label: "",
                name: RouteNames.ViewLessonDay,
                header: "View Lesson Day",
                route: "/auth/course-level/:courseLevelId/lesson-days/:id/view",
            },
        ],
    },
    {
        label: "Rest Videos",
        name: "rest_video_group",
        icon: Video,
        route: "/auth/rest-videos",
        children: [
            {
                label: "Rest Video List",
                name: RouteNames.RestDayVideosList,
                header: "Rest Video Management",
                route: "/auth/rest-videos",
            },
            {
                label: "",
                name: RouteNames.AddRestDayVideo,
                header: "Add Rest Video",
                route: "/auth/rest-videos/add",
            },
            {
                label: "",
                name: RouteNames.EditRestDayVideo,
                header: "Edit Rest Video",
                route: "",
            },
            {
                label: "",
                name: RouteNames.ViewRestDayVideo,
                header: "View Rest Video",
                route: "",
            },
        ],
    },
    {
        label: "Featured Images",
        name: "featured_image_group",
        icon: Image,
        route: "/auth/featured-images",
        children: [
            {
                label: "Featured Image List",
                name: RouteNames.FeaturedImagesList,
                header: "Featured Image Management",
                route: "/auth/featured-images",
            },
            {
                label: "",
                name: RouteNames.AddFeaturedImage,
                header: "Add Featured Image",
                route: "/auth/featured-images/add",
            },
            {
                label: "",
                name: RouteNames.EditFeaturedImage,
                header: "Edit Featured Image",
                route: "",
            },
            {
                label: "",
                name: RouteNames.ViewFeaturedImage,
                header: "View Featured Image",
                route: "",
            },
        ],
    },
    {
        label: "Walk In",
        name: "walk_in_group",
        icon: Banknote,
        route: "/auth/walk-in",
        children: [
            {
                label: "Walk In List",
                name: RouteNames.WalkInsList,
                header: "Walk In Management",
                route: "/auth/walk-in",
            },
        ],
    },
];
