/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminsChangePasswordForm: typeof import('./../../views/components/admins/AdminsChangePasswordForm.vue')['default']
    AdminsFilter: typeof import('./../../views/components/admins/AdminsFilter.vue')['default']
    AdminsForm: typeof import('./../../views/components/admins/AdminsForm.vue')['default']
    AdminsList: typeof import('./../../views/components/admins/AdminsList.vue')['default']
    App: typeof import('./../../views/components/App.vue')['default']
    BaseFilter: typeof import('./../../views/components/common/filter/BaseFilter.vue')['default']
    ConfirmDialog: typeof import('./../../views/components/common/dialog/ConfirmDialog.vue')['default']
    CourseCategoriesFilter: typeof import('./../../views/components/course-categories/CourseCategoriesFilter.vue')['default']
    CourseCategoriesForm: typeof import('./../../views/components/course-categories/CourseCategoriesForm.vue')['default']
    CourseCategoriesList: typeof import('./../../views/components/course-categories/CourseCategoriesList.vue')['default']
    CourseCategoryForm: typeof import('./../../views/components/course-categories/CourseCategoryForm.vue')['default']
    CourseDayForm: typeof import('./../../views/components/course-days/CourseDayForm.vue')['default']
    CourseDaysFilter: typeof import('./../../views/components/course-days/CourseDaysFilter.vue')['default']
    CourseDaysForm: typeof import('./../../views/components/course-days/CourseDaysForm.vue')['default']
    CourseDaysList: typeof import('./../../views/components/course-days/CourseDaysList.vue')['default']
    CoursesFilter: typeof import('./../../views/components/courses/CoursesFilter.vue')['default']
    CoursesForm: typeof import('./../../views/components/courses/CoursesForm.vue')['default']
    CoursesList: typeof import('./../../views/components/courses/CoursesList.vue')['default']
    CustomDialog: typeof import('./../../views/components/common/dialog/CustomDialog.vue')['default']
    DataTable: typeof import('./../../views/components/common/data-table/DataTable.vue')['default']
    DepositsFilter: typeof import('./../../views/components/deposits/DepositsFilter.vue')['default']
    DepositsForm: typeof import('./../../views/components/deposits/DepositsForm.vue')['default']
    DepositsList: typeof import('./../../views/components/deposits/DepositsList.vue')['default']
    FormImage: typeof import('./../../views/components/common/formControl/FormImage.vue')['default']
    FormInput: typeof import('./../../views/components/common/formControl/FormInput.vue')['default']
    FormSelect: typeof import('./../../views/components/common/formControl/FormSelect.vue')['default']
    Gallary: typeof import('./../../views/components/common/gallary/Gallary.vue')['default']
    Header: typeof import('./../../views/components/layouts/Header.vue')['default']
    Login: typeof import('./../../views/components/login/Login.vue')['default']
    PackagesFilter: typeof import('./../../views/components/packages/PackagesFilter.vue')['default']
    PackagesForm: typeof import('./../../views/components/packages/PackagesForm.vue')['default']
    PackagesList: typeof import('./../../views/components/packages/PackagesList.vue')['default']
    Pagination: typeof import('./../../views/components/pagination/Pagination.vue')['default']
    PaymentMethodsFilter: typeof import('./../../views/components/payment-methods/PaymentMethodsFilter.vue')['default']
    PaymentMethodsForm: typeof import('./../../views/components/payment-methods/PaymentMethodsForm.vue')['default']
    PaymentMethodsList: typeof import('./../../views/components/payment-methods/PaymentMethodsList.vue')['default']
    PurchasesFilter: typeof import('./../../views/components/purchases/PurchasesFilter.vue')['default']
    PurchasesForm: typeof import('./../../views/components/purchases/PurchasesForm.vue')['default']
    PurchasesList: typeof import('./../../views/components/purchases/PurchasesList.vue')['default']
    RootLayout: typeof import('./../../views/components/layouts/RootLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./../../views/components/layouts/Sidebar.vue')['default']
    TableSkeletonLoader: typeof import('./../../views/components/common/skeleton-loader/TableSkeletonLoader.vue')['default']
    Unauthorized: typeof import('./../../views/components/unauthorized/Unauthorized.vue')['default']
    UsersFilter: typeof import('./../../views/components/users/UsersFilter.vue')['default']
    UsersForm: typeof import('./../../views/components/users/UsersForm.vue')['default']
    UsersList: typeof import('./../../views/components/users/UsersList.vue')['default']
    UsersPasswordChangeForm: typeof import('./../../views/components/users/UsersPasswordChangeForm.vue')['default']
  }
}
