/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminFilter: typeof import('./../../views/components/admin/AdminFilter.vue')['default']
    AdminForm: typeof import('./../../views/components/admin/AdminForm.vue')['default']
    AdminList: typeof import('./../../views/components/admin/AdminList.vue')['default']
    App: typeof import('./../../views/components/App.vue')['default']
    ConfirmDialog: typeof import('./../../views/components/dialog/ConfirmDialog.vue')['default']
    ConfirmModal: typeof import('./../../views/components/common/modal/ConfirmModal.vue')['default']
    CustomDialog: typeof import('./../../views/components/dialog/CustomDialog.vue')['default']
    CustomModal: typeof import('./../../views/components/common/modal/CustomModal.vue')['default']
    DataTable: typeof import('./../../views/components/data-table/DataTable.vue')['default']
    FormImage: typeof import('./../../views/components/common/formControl/FormImage.vue')['default']
    FormInput: typeof import('./../../views/components/common/formControl/FormInput.vue')['default']
    FormSelect: typeof import('./../../views/components/common/formControl/FormSelect.vue')['default']
    Header: typeof import('./../../views/components/layouts/Header.vue')['default']
    Login: typeof import('./../../views/components/login/Login.vue')['default']
    PaymentFilter: typeof import('./../../views/components/payment/PaymentFilter.vue')['default']
    PaymentForm: typeof import('./../../views/components/payment/PaymentForm.vue')['default']
    PaymentList: typeof import('./../../views/components/payment/PaymentList.vue')['default']
    RootLayout: typeof import('./../../views/components/layouts/RootLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./../../views/components/layouts/Sidebar.vue')['default']
    UserFilter: typeof import('./../../views/components/user/UserFilter.vue')['default']
    UserForm: typeof import('./../../views/components/user/UserForm.vue')['default']
    UserList: typeof import('./../../views/components/user/UserList.vue')['default']
  }
}
